package extractor;

import org.apache.commons.lang3.Range;

import utils.PtbUtils;
import annotation.ISimpAnnotations.AdjpCoordinationAnnotation;
import annotation.ISimpAnnotations.AdvpCoordinationAnnotation;
import annotation.ISimpAnnotations.CoordinationAnnotation;
import annotation.ISimpAnnotations.CoordinationConjunctAnnotation;
import annotation.ISimpAnnotations.CoordinationConjunctionAnnotation;
import annotation.ISimpAnnotations.NpCoordinationAnnotation;
import annotation.ISimpAnnotations.PpCoordinationA